/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Building7(props) {
    const { nodes, materials } = useGLTF('/elements/Buildin7.glb')
    return (
        <group {...props} dispose={null} position={[0, -.35, 0]} rotation={[0, 0, 0]}>
            <RigidBody colliders="trimesh" type='fixed'>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.building_D.geometry}
                    material={materials.citybits_texture}
                    scale={400}
                />
            </RigidBody>

        </group>
    )
}

useGLTF.preload('/elements/Buildin7.glb')
