/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EmitPrincipal(props) {
  const { nodes, materials } = useGLTF('/object3d/emit.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.Material}
        position={[12, 4.5, -0.2]}
        scale={[2, 1.5, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Matériau}
        position={[0, 3.8, 1.6]}
        scale={[2, 0.5, 0.2]}
      />
    </group>
  )
}

useGLTF.preload('/object3d/emit.glb')
