/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zordew (https://sketchfab.com/zordewgfx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f1-tyres-pack-2022-hard-medium-soft-307a0557dde44cf1a7f6f2d1958c383d
Title: F1 TYRES PACK 2022 - HARD - MEDIUM - SOFT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function F1Tyre(props) {
  const { nodes, materials } = useGLTF('/object3d/f1_tyres_pack_2022_-_hard_-_medium_-_soft.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.921, 0.274, 0.909]} scale={2.182}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['MEDIUM_TYRE.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.BRAKES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.SCREW}
        />
      </group>
      <group position={[-0.921, 0.274, 1.799]} scale={2.182}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.SOFT_TYRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.BRAKES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.SCREW}
        />
      </group>
      <group position={[-0.921, 0.274, 0.039]} scale={2.182}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.HARD_TYRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.BRAKES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.SCREW}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/object3d/f1_tyres_pack_2022_-_hard_-_medium_-_soft.glb')
