/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hospital({ isNight, ...props }) {
    const { nodes, materials } = useGLTF('/object3d/Hospital.glb')
    return (
        <>
            <pointLight
                position={[0, 5, 0]}
                color="white"
                intensity={isNight ? 500 : 0}
                distance={50}
                decay={2}
            />
            <group {...props} dispose={null} position={[0, 4, 0]} scale={.04}>
                <mesh castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.Cube} />
            </group>
        </>

    )
}

useGLTF.preload('/object3d/Hospital.glb')
