/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Redgrund (https://sketchfab.com/redgrund)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-mcl60-f1-2023-8340e27c325345e4aa92a6a31cc34b1e
Title: McLaren MCL60 F1 2023
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mclaren(props) {
  const { nodes, materials } = useGLTF('/object3d/McLaren.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Material}
      />
    </group>
  )
}

useGLTF.preload('/object3d/McLaren.glb')



