/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bunny (https://sketchfab.com/YolandaX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/post-office-50d2264945ec49fbaec551d0e58eae71
Title: Post Office
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PostOffice({ isNight, ...props }) {
    const { nodes, materials } = useGLTF('/object3d/post_office.glb')
    return (
        <group {...props} dispose={null}>
            <pointLight
                position={[0, 1, 0]}
                color="white"
                intensity={isNight ? 50 : 0}
                distance={20}
                decay={2}
            />
            <group position={[0.005, 1.751, 0.001]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials['.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['.002']}
                />
            </group>
            <group
                position={[-0.025, 2.57, 2.322]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[1.171, 2.418, 0.869]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials['.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials['.006']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_7.geometry}
                material={materials.material}
                position={[0.005, 1.751, -0.059]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_9.geometry}
                material={materials['.003']}
                position={[0.995, 1.934, 2.331]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={1.026}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_11.geometry}
                material={materials.material}
                position={[-1.317, 1.483, 2.282]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_13.geometry}
                material={materials['.003']}
                position={[-1.317, 1.592, 2.285]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_15.geometry}
                material={materials['.004']}
                position={[-0.796, 1.301, 2.329]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.025, 0.037, 0.025]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials['.007']}
                position={[-2.79, 2.717, 1.441]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[0.136, 0.176, 0.136]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials['.006']}
                position={[-2.892, 2.717, 1.441]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[0.2, 0.038, 0.2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials['.008']}
                position={[0.014, 5.613, 2.357]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={0.91}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials['.004']}
                position={[-1.256, 4.415, 2.385]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.053, 0.14, 0.053]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials['.004']}
                position={[1.263, 4.415, 2.385]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.053, 0.14, 0.053]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials['.006']}
                position={[-3.38, 0.495, 0.569]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.509, 0.681, 0.681]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_32.geometry}
                material={materials['.010']}
                position={[-3.38, 0.495, 1.515]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.509, 0.681, 0.681]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials['.011']}
                position={[0.005, 0, 0.001]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={4.291}
            />
        </group>
    )
}

useGLTF.preload('/object3d/post_office.glb')