/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RadioTower({ isNight, ...props }) {
    const { nodes, materials } = useGLTF('/object3d/Radio tower.glb')
    return (
        <>
            <pointLight
                position={[0, 28, 4]}
                color="red"
                intensity={isNight ? 50 : 0}
                distance={50}
                decay={2}
            />
             <pointLight
                position={[0, 28, -4]}
                color="red"
                intensity={isNight ? 50 : 0}
                distance={50}
                decay={2}
            />
             <pointLight
                position={[4, 28, 0]}
                color="red"
                intensity={isNight ? 50 : 0}
                distance={50}
                decay={2}
            />
             <pointLight
                position={[-4, 28, 0]}
                color="red"
                intensity={isNight ? 50 : 0}
                distance={50}
                decay={2}
            />
            <group {...props} dispose={null} position={[0, 22.7, 0]} rotation={[0, Math.PI / 2, 0]} scale={10}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.radio_tower.geometry}
                    material={materials.None}
                />
            </group>
        </>
    )
}

useGLTF.preload('/object3d/Radio tower.glb')
