/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import { useDayNight } from '../../contexts/DayNightContext';
import { useFrame, useThree } from '@react-three/fiber';
import { RigidBody } from '@react-three/rapier';

const MAX_LIGHT_DISTANCE = 50;

export function RadioTower({ ...props }) {
    const { nodes, materials } = useGLTF('/elements/Radio tower.glb')
    const { isNight } = useDayNight();
    const lightRef = useRef();
    const { camera } = useThree();

    useFrame(() => {
        if (!lightRef.current) return;

        const lanternPos = lightRef.current.getWorldPosition(new THREE.Vector3());
        const distance = lanternPos.distanceTo(camera.position);

        const shouldLight = isNight && distance < MAX_LIGHT_DISTANCE;
        const targetIntensity = shouldLight ? 30 : 0;

        lightRef.current.intensity = THREE.MathUtils.lerp(
            lightRef.current.intensity,
            targetIntensity,
            0.1 // Vitesse de fade
        );
    });

    return (
        <>
            <pointLight
                ref={lightRef}
                position={[0, 28, 0]}
                color="red"
                intensity={0}
                distance={20}
                decay={1}
            />
            <RigidBody colliders="trimesh" type='fixed'>
                <group {...props} dispose={null} position={[0, 22.7, 0]} rotation={[0, Math.PI / 2, 0]} scale={10}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.radio_tower.geometry}
                        material={materials.None}
                    />
                </group>
            </RigidBody>

        </>
    )
}

useGLTF.preload('/elements/Radio tower.glb')
