/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: juro.bednarik (https://sketchfab.com/juro.bednarik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/factory-lowpoly-free-0a8f602a4714400f9f66365ded7a9215
Title: Factory lowpoly free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RedFactory({ isNight, ...props }) {
    const { nodes, materials } = useGLTF('/object3d/factory_lowpoly_free.glb')
    return (
        <group {...props} dispose={null}>
            <pointLight
                position={[0, 10, 0]}
                color="white"
                intensity={isNight ? 500 : 0}
                distance={50}
                decay={2}
            />
            <group scale={0.03}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.factory_texture_factory_0.geometry}
                    material={materials.texture_factory}
                    position={[-27.925, 10.074, -37.812]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/object3d/factory_lowpoly_free.glb')
