/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Server(props) {
  const { nodes, materials } = useGLTF(
    "/object3d/server rack.glb"
  );
  return (
    <group {...props} dispose={null} scale={.5}>
      <RigidBody type="fixed" colliders="cuboid">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.console.geometry}
          material={materials.console_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.console_base_right.geometry}
          material={materials.Cube1_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.console_left.geometry}
          material={materials.Cube1_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.misc1.geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["2u_nas1"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.misc2.geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ups.geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server9"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server8"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server7"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server6"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server5"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server4"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server3"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server2"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["1u_server1"].geometry}
          material={materials.Cube12_auv}
        />
        <mesh castShadow receiveShadow geometry={nodes.rack.geometry}>
          <meshStandardMaterial color="#A9A9A9" />
        </mesh>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/object3d/server rack.glb");
