/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Virginia Vidonis (https://sketchfab.com/virginiavidonis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-shop-0013cf5979c846449c817a2439fd8705
Title: Low Poly Shop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shop(props) {
  const { nodes, materials } = useGLTF('/object3d/low_poly_shop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-198.994, 137.996, -155.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_frontale_sx_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_frontale_sx_vetri_0.geometry}
            material={materials.vetri}
          />
        </group>
        <group
          position={[49.003, 137.996, 363.258]}
          rotation={[-Math.PI / 2, 0, 1.571]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_facciata_dx_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_facciata_dx_vetri_0.geometry}
            material={materials.vetri}
          />
        </group>
        <group position={[8.133, -25.794, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_dx_vetri_0.geometry}
            material={materials.vetri}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_dx_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
        </group>
        <group position={[0, -28.049, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_sx_vetri_0.geometry}
            material={materials.vetri}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.finestra_sx_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
        </group>
        <group
          position={[-131.537, 137.591, 15.545]}
          rotation={[-Math.PI / 2, 0, 0.536]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.porta_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.porta_vetri_0.geometry}
            material={materials.vetri}
          />
        </group>
        <group
          position={[-224.788, 233.72, -91.684]}
          rotation={[-Math.PI / 2, 0, 0.001]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_bianco_0.geometry}
            material={materials.bianco}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
        </group>
        <group
          position={[-71.312, 233.72, -374.482]}
          rotation={[-Math.PI / 2, 0, -1.57]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale001_bianco_0.geometry}
            material={materials.bianco}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale001_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
        </group>
        <group
          position={[-140.322, 233.72, 287.752]}
          rotation={[-Math.PI / 2, 0, 0.001]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_piccola_bianco_0.geometry}
            material={materials.bianco}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_piccola_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
        </group>
        <group
          position={[117.332, 237.722, 396.082]}
          rotation={[-Math.PI / 2, 0, 1.57]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_facciata_dx_porta_e_serramenti_0.geometry}
            material={materials.porta_e_serramenti}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tenda_frontale_facciata_dx_bianco_0.geometry}
            material={materials.bianco}
          />
        </group>
        <group position={[69.985, 316.903, -168.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassetta_bianco_0.geometry}
            material={materials.bianco}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cassetta_nero_0.geometry}
            material={materials.nero}
          />
        </group>
        <group
          position={[-197.371, 10.652, -213.451]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vaso_rettangolare_sx_3_VASI_0.geometry}
            material={materials.VASI}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vaso_rettangolare_sx_3_TERRA_0.geometry}
            material={materials.TERRA}
          />
        </group>
        <group
          position={[-197.371, 10.652, -105.697]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vaso_rettangolare_sx_3002_VASI002_0.geometry}
            material={materials['VASI.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vaso_rettangolare_sx_3002_TERRA002_0.geometry}
            material={materials['TERRA.002']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base001_base_0.geometry}
          material={materials.base}
          position={[0, 7.744, 7.22]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tetto_casa_base_0.geometry}
          material={materials.casa_base}
          position={[0, 130.791, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.casa_base_casa_base_0.geometry}
          material={materials.casa_base}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base_base_condizionatore_0.geometry}
          material={materials.base_condizionatore}
          position={[69.985, 304.157, -168.012]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tubo_tubo_0.geometry}
          material={materials.tubo}
          position={[80.91, 325.703, -222.907]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base_tubo_tubo_0.geometry}
          material={materials.tubo}
          position={[80.847, 302.177, -224.081]}
          rotation={[-Math.PI / 2, 0, -0.394]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_nero_0.geometry}
          material={materials.nero}
          position={[71.28, 333.737, -156.16]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_CESPUGLI_0.geometry}
          material={materials.CESPUGLI}
          position={[-197.363, 18.101, -225.966]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003_CESPUGLI_0.geometry}
          material={materials.CESPUGLI}
          position={[-197.296, 17.55, -222.187]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002_CESPUGLI001_0.geometry}
          material={materials['CESPUGLI.001']}
          position={[-197.363, 16.251, -116.374]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001_CESPUGLI001_0.geometry}
          material={materials['CESPUGLI.001']}
          position={[-197.296, 15.7, -113.658]}
          rotation={[-Math.PI / 2, 0, 1.572]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/object3d/low_poly_shop.glb')
