/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Text } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function WoodSign({...props }) {
    const { nodes, materials } = useGLTF('/elements/Wooden Sign.glb')
    return (
        <group {...props} dispose={null}>
            <RigidBody colliders="trimesh" type="fixed" position={[0, 0, 0]}>
                <group scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Sign4_1.geometry}
                        material={materials['Dark Wood']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Sign4_2.geometry}
                        material={materials['Light Wood']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Sign4_3.geometry}
                        material={materials.Rocks}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Sign4_4.geometry}
                        material={materials.Herbs}
                    />
                    
            
                </group>
            </RigidBody>
        </group>
    )
}

useGLTF.preload('/elements/Wooden Sign.glb')