/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Cobblestone(props) {
  const { nodes, materials } = useGLTF('/elements/Cobblestone tile.glb')
  return (
    <RigidBody colliders="cuboid" type='fixed' position={[0, 0, 0]}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.path_A.geometry}
          material={materials.HalloweenBits}
          scale={100}
        />
      </group>
    </RigidBody>

  )
}

useGLTF.preload('/elements/Cobblestone tile.glb')