/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lupas (https://sketchfab.com/ivan.anton.albarracin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-trees-and-bushes-a30ce304c137481b87dfa1223c4fc796
Title: simple low poly trees and bushes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'


export function Sapin1(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree020_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree020_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>

    </group>
  )
}

export function Sapin2(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree019_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree019_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>

    </group>
  )
}

export function Tree1(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree013_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree013_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>

    </group>
  )
}

export function Tree2(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree011_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree011_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>
    </group>
  )
}

export function Tree3(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree005_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree005_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>
    </group>
  )
}

export function Tree4(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <group position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree003_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree003_green_0.geometry}
            material={materials.green}
          />
        </group>
      </RigidBody>
    </group>
  )
}


export function DeathTree1(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree023_wood_0.geometry}
          material={materials.wood}
          position={[0, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </RigidBody>
    </group>
  )
}

export function DeathTree2(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree022_wood_0.geometry}
          material={materials.wood}
          position={[0, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </RigidBody>
    </group>
  )
}


export function DeathTree3(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree018_wood_0.geometry}
          material={materials.wood}
          position={[0, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </RigidBody>
    </group>
  )
}

export function DeathTree4(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree001_wood_0.geometry}
          material={materials.wood}
          position={[0, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </RigidBody>
    </group>
  )
}

export function Bush(props) {
  const { nodes, materials } = useGLTF('/elements/simple_low_poly_trees_and_bushes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bush002_green_0.geometry}
        material={materials.green}
        position={[0, 0, 0]}
        rotation={[0, 0, Math.PI / 2]}
      />
    </group>
  )
}

useGLTF.preload('/elements/simple_low_poly_trees_and_bushes.glb')