/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function TrafficLight(props) {
  const { nodes, materials } = useGLTF(
    "/elements/Traffic Light.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrafficLight_1.geometry}
        material={materials["Atlas.051"]}
        scale={100}
      />
      <RigidBody type="fixed" position={[0, 0, 0]} colliders="cuboid">
        <mesh >
          <boxGeometry args={[.3, 7, .3]} />
          <meshBasicMaterial color="red" transparent opacity={0} />
        </mesh>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/elements/Traffic Light.glb");
