/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Turn(props) {
  const { nodes, materials } = useGLTF(
    "/elements/Street Turn.glb"
  );
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="cuboid">
     
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Street_Turn.geometry}
          material={materials["Atlas.006"]}
          scale={100}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/Element3D/environement/ways/Street Turn.glb");
